version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - '2000:2000'
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
