name: Deploy Shamos YouTube Downloader to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: shamostechsoluti-1691658123783
      VM_NAME: shamos
      ZONE: us-central1-b
      REPOSITORY: shamos-youtube-downloader

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker Authentication for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/shamos-youtube-downloader-full:latest .
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/shamos-youtube-downloader-full:latest

    - name: Deploy to VM
      run: |
        gcloud compute ssh $VM_NAME --zone $ZONE --command "
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet &&
          sudo docker login -u oauth2accesstoken -p \"$(gcloud auth print-access-token)\" https://us-central1-docker.pkg.dev &&
          sudo docker pull us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/shamos-youtube-downloader-full:latest &&
          sudo docker stop shamos-youtube-downloader-full || true &&
          sudo docker rm -f shamos-youtube-downloader-full || true &&
          sudo docker system prune -af &&
          sudo docker run -d --name shamos-youtube-downloader-full -p 2000:3000 us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/shamos-youtube-downloader-full:latest &&
          sudo systemctl reload nginx
        "
